### ISSUE TITLE
Tests fail

### ISSUE THREAD

**Issue by lxbarth** [osmcode/node-osmium#40] opened 2015-04-25 16:44 UTC
Just installed and tested, failed like below. This was latest version from master (5e06eac0bdb0cd863f62740a0945cc9aaa5d21b3). mocha and node versions as below in log.

    ab:node-osmium ab$ npm install
    npm WARN engineStrict Per-package engineStrict (found in package.json for node-pre-gyp)
    npm WARN engineStrict won't be used in npm 3+. Use the config setting `engine-strict` instead.
    \
    > osmium@0.3.0 install /Users/ab/apps/node-osmium
    > node-pre-gyp install --fallback-to-build

    [osmium] Success: "/Users/ab/apps/node-osmium/lib/binding/osmium.node" is installed via remote
    mocha@2.2.4 node_modules/mocha
    ├── escape-string-regexp@1.0.2
    ├── supports-color@1.2.1
    ├── diff@1.0.8
    ├── commander@2.3.0
    ├── growl@1.8.1
    ├── debug@2.0.0 (ms@0.6.2)
    ├── jade@0.26.3 (commander@0.6.1, mkdirp@0.3.0)
    ├── mkdirp@0.5.0 (minimist@0.0.8)
    └── glob@3.2.3 (inherits@2.0.1, graceful-fs@2.0.3, minimatch@0.2.14)

    aws-sdk@2.0.12 node_modules/aws-sdk
    ├── xmlbuilder@0.4.2
    ├── aws-sdk-apis@3.1.10
    └── xml2js@0.2.6 (sax@0.4.2)

    node-pre-gyp@0.6.4 node_modules/node-pre-gyp

    ab:node-osmium ab$ make test

      apply
        1) should be able to call apply with a node Buffer and a handler

      reader
        ✓ should throw when BasicReader called as function
        2) should be able to create an osmium.BasicReader and access header
        3) should be able to create osmium.File with node.Buffer and read from it
        4) should read a whole file with BasicReader.read_all()

      buffer
        5) should allow reading into buffer
        6) should allow reading into buffer in a loop
        7) should allow iterating over buffer
        8) should be able to stream buffer created from a file
    /bin/sh: line 1: 47309 Segmentation fault: 11  NODE_PATH="./lib:" mocha -R spec --timeout 10s
    make: *** [test] Error 139

    ab:node-osmium ab$ which node
    /Users/ab/.nvm/v0.10.20/bin/node

    ab:node-osmium ab$ mocha --version
    2.2.4

**Comment by springmeyer** [comment] 2015-04-30 19:43
This crash is fixed in master. The problem is that `npm install` is bringing in binaries from the older v0.3.0 release currently (I need to fix this). The v0.3.0 is still good to go for most purposes in the meantime. For example I confirmed that all the tests for v0.3.0 work fine with the v0.3.0 binaries:

```
git checkout v0.3.0
npm test
```

**Comment by springmeyer** [comment] 2015-05-05 01:31
fixed by 2c5d20aba0a97

**Closed by springmeyer** 2015-05-05 01:31 UTC
